### ISSUE TITLE
Top left corner minor glitch

### ISSUE THREAD

**Issue by linxlan** [tsujan/BreezeEnhanced#37] opened 2022-04-03 18:30 UTC
As you can see on the screenshots there is minor glitch in top left corner. Here is how it looks in default Breeze (right picture) in compare to BreezeEnhanced (left picture). I'm using KDE 5.24.4

![1](https://user-images.githubusercontent.com/29060641/161442573-8c849d50-8bc5-499a-8a9a-71acecc5cc2d.png)
![2](https://user-images.githubusercontent.com/29060641/161442579-14ac94aa-ec69-4773-a568-11991fde6784.png)

**Comment by tsujan** [comment] 2022-04-03 18:43
Is KDE's blur effect active in your system?

**Comment by linxlan** [comment] 2022-04-03 18:46
Yes, and turning it off fixes the issue. But there is any option to disable blur just for window decoration, not system wide?

**Comment by tsujan** [comment] 2022-04-03 19:05
This is the "infamous" blur glitch. It isn't caused by BreezeEnhanced.

> But there is any option to disable blur just for window decoration, not system wide?

No, there isn't. BreezeEnhanced can either support it or not support it. The code structure, which is inherited from Breeze, doesn't allow an option for it. Of course, we want to support it.

That being said, I'll see if a simple trick could be found. But no promise, especially because I don't have time to maintain a code very different from that of Breeze.

**Comment by trmdi** [comment] 2022-04-03 19:09
Is this the infamous korner bug right? If so you can fix it by setting the blurred region: https://invent.kde.org/plasma/kdecoration/-/commit/fb56349603067463ffef1ea158fd7a6c10d26e0f

**Comment by linxlan** [comment] 2022-04-03 19:10
I don't think code will be very different from default Breeze. Default Breeze doesn't have this issue, it works fine with blur enabled.

**Comment by tsujan** [comment] 2022-04-03 19:20
> Is this the infamous korner bug right? If so you can fix it by setting the blurred region

Neither Breeze nor BreezeEnhanced does blurring. It's done at a lower level.

> Default Breeze doesn't have this issue

Because it doesn't enable blurring. As I said, the Breeze code allows either ignoring or enabling blurring, without an option.

**Comment by tsujan** [comment] 2022-04-03 20:26
OK, apparently, the API is limited (→ https://api.kde.org/plasma/kdecoration/html/index.html). They suppose that you either need or don't need the blur effect. No option.

If you want to keep the blur effect but don't want it with the decoration, you could set the value of `org.kde.kdecoration2 → blur` to `false` in `BreezeEnhanced/breeze.json` and recompile BreezeEnhanced. That's how Breeze does it.

Of course, I've set it to `true` intentionally; BreezeEnhanced should support translucency + Blurring.

As for the corner bug, it has been there for a long time. Recently, there has been some activity in the direction of fixing it, but it should be fixed upstream.

**Closed by tsujan** 2022-04-03 20:26 UTC

**Comment by trmdi** [comment] 2022-04-04 08:31
That will be changed in KWin 5.15: https://psifidotos.blogspot.com/2022/03/kornersfix.html

**Comment by tsujan** [comment] 2022-04-04 09:11
> That will be changed in KWin 5.15: https://psifidotos.blogspot.com/2022/03/kornersfix.html

If KWin 5.25 allows setting of the blurred region, yes, it'll be possible to get rid of blur glitches, like what is done in Kvantum (where I added two parameters for blur radii of menus and tooltips).

**Comment by tsujan** [comment] 2022-06-20 14:12
KWin 5.25 has been released. The blur effect is disabled by it. It hasn't come to my distro yet (will come soon) , but I prepared a patch for re-enabling the blur effect without corner glitches, based on `KDecoration2::Decoration::setBlurRegion()`. Once KWin 5.25 comes here, I'll test and complete the patch.

**Comment by tsujan** [comment] 2022-07-21 23:36
Sorry for the long delay. Apparently, Manjaro Testing (my distro) has protected its users from bugs in Plasma 5.25. I still have kwin 5.24.6; don't know if 5.25 will come here or Manjaro Testing will jump to 5.26 when it's released.

This had never happened before. I just searched and found several reports about bad bugs in 5.25.

**Comment by tsujan** [comment] 2022-08-24 00:01
Done at last (in https://github.com/tsujan/BreezeEnhanced/commit/e9235c91724913a2cf3153d7e47b963917e51677).

The code I'd prepared before 5.25 worked fine. No corner glitches anymore, thanks to the changes in the new KWin. Please upgrade and test it!
