### ISSUE TITLE
Decoration artifact on hovering

### ISSUE THREAD

**Issue by kupiqu** [tsujan/BreezeEnhanced#10] opened 2018-11-07 19:40 UTC
Please see the attached screenshot:

![image](https://user-images.githubusercontent.com/3875196/48155924-19c54600-e29a-11e8-8a8a-c700974955bc.png)

No idea where these artifacts come from. They seem to happen randomly, always on hovering, and then stay there. This happens for both active and inactive windows. The number of buttons affected seems quite random too, sometimes they affect just one button (like in the screenshot), sometimes 2 or 3 consecutive buttons.

It could be an upstream bug in breeze, kwin or qt, but somehow I failed to reproduce the issue in breeze.

**Comment by tsujan** [comment] 2018-11-07 19:50
Can't reproduce, although I only use BreezeEnhanced.

Are you sure you've compiled it against the same version of KWin? V5.14 shouldn't be compiled with older KWin versions.

**Comment by tsujan** [comment] 2018-11-07 20:12
@trmdi Sorry to bother you! Can you reproduce this isse?

**Comment by kupiqu** [comment] 2018-11-07 20:16
Yes, I compile BreezeEnhanced against plasma 5.14

It may be driver dependent, perhaps?

**Comment by kupiqu** [comment] 2018-11-07 21:01
```
[Common]
OutlineCloseButton=false
ShadowStrength=89

[Style]
ScrollBarAddLineButtons=0
ScrollBarSubLineButtons=0
WindowDragMode=WD_MINIMAL

[Windeco]
ButtonHPadding=4
ButtonSpacing=0
DrawBackgroundGradient=false
DrawSizeGrip=false
DrawTitleBarSeparator=false
TitleAlignment=AlignRight
TitleBarFont=Cabin [IMPA],10,-1,5,50,0,0,0,0,0
matchColorForTitleBar=false
```

**Comment by tsujan** [comment] 2018-11-07 21:09
Thanks! I'll test it as soon as I find some time -- being very busy right now.

**Comment by kupiqu** [comment] 2018-11-07 21:11
thank you

**Comment by tsujan** [comment] 2018-11-07 23:34
I tested with your configuration but everything was OK. I wasn't able to find anything in the code that might cause the problem you described: ~90% of the code is that of Breeze and a simple animation shouldn't cause this. If your driver had a problem, you would see similar effects elsewhere (do you?).

So, for now, the only things that comes to my mind are that you might want (1) to test with another KDE color scheme or (2) to recompile BreezeEnhanced and restart KWin.

I'll keep this open to see if others encounter it or if something else comes to my mind.

**Comment by trmdi** [comment] 2018-11-08 01:19
Sorry, I don't see any problem with that screenshot ???

**Comment by trmdi** [comment] 2018-11-08 02:05
Do you mean the blue border around the middle buton ? I've never seen that too.
@kupiqu Did you try turning off the `vsync` or change the `openGL version` in SystemSetting > Compositor?

**Comment by tsujan** [comment] 2018-11-08 02:16
> Do you mean the blue border around the middle buton ? I've never seen that too.

Yes. I think if there is a problem with grahic driver or vsync, @kupiqu should see similar issues in other places too.

**Comment by kupiqu** [comment] 2018-11-08 03:39
I think it may be driver-dependent, although I didn't notice any issue elsewhere. Changing Vsync didn't help, neither modifying the OpenGL version, but I don't see the artifacts when I instead use XRender.

It all seems to indicate this is an upstream issue, so think I'll close the issue for now while I explore the root cause further...

Thank you @tsujan and @trmdi for your feedback!

**Comment by ripefig** [comment] 2018-11-27 18:17
@tsujan I can reproduce this. This happens when the blur desktop effect is enabled and happens more frequently when you use window shading. Shade a window (I have unshade on hover too) and you should see this. I have Open GL 2.0 and integrated graphics.

![image 2018-11-27 21-08](https://user-images.githubusercontent.com/45201036/49102131-0863ce00-f289-11e8-8bfb-aa2d79ecfa9a.gif)

**Comment by tsujan** [comment] 2018-11-27 18:37
@ripefig, thanks for your feedback! Now, I really think this may be related to the graphic driver/settings because I've NEVER seen it here. I can't think of anything in BreezeEnhanced that might cause it: the animation was already there; I just made use of it. But the quality of the blur effect is highly dependent on the graphic driver/settings.

That being said, I keep it in mind. Please let me know if it disappears with a KDE/KWin upgrade or a change in graphic driver/settings.

**Comment by kupiqu** [comment] 2018-11-27 18:40
> I really think this may be related to the graphic driver

I agree

**Comment by tsujan** [comment] 2018-11-27 18:53
> or a bug in kwin

That's quite possible. In 2017, I couldn't use KWin because it was so lagging, while I had a powerful computer. I reported the problem but no solution was found. A year later, the problem was completely gone after multiple upgrades. Since then, I use nothing but KWin.

**Comment by kupiqu** [comment] 2018-11-27 18:56
> That's quite possible. In 2017, I couldn't use KWin because it was so lagging, while I had a powerful computer. I reported the problem but no solution was found. A year later, the problem was completely gone after multiple upgrades. Since then, I use nothing but KWin.

Reminder to ourselves (/me and @ripefig): we should check this out in wayland...

**Comment by kupiqu** [comment] 2018-11-28 02:17
> Reminder to ourselves (/me and @ripefig): we should check this out in wayland...

I do think it's a kwin bug, no need to go wayland actually, because exactly the same animations in the applet-window-buttons never create such artifacts

**Comment by kupiqu** [comment] 2018-11-28 02:42
I filled a bug in kde about this: 
https://bugs.kde.org/show_bug.cgi?id=401492

**Comment by trmdi** [comment] 2018-11-28 02:49
But I guess it would be very difficult to make they test 3rd plugins...

**Comment by kupiqu** [comment] 2018-11-28 02:56
well, I guess it depends on how much evidence we report suggesting that the issue is in kwin (even though it is hidden by the fact that vanilla breeze does not have button animations), and mentioning about plasma, where the same animations work fine seems to indicate so.

**Comment by trmdi** [comment] 2018-11-28 03:00
@kupiqu @ripefig 
Did you try some workaround in this? https://wiki.archlinux.org/index.php/intel_graphics#Troubleshooting

**Comment by kupiqu** [comment] 2018-11-28 03:08
> But I guess it would be very difficult to make they test 3rd plugins. Furthermore, not everyone has this bug. You have to find a reliable way to reproduce it.

I can reproduce it all the time in my system. To reproduce it, you need intel+opengl, but yes, most likely not all intel+opengl cause the artifacts. Added more info to kde bug...

**Comment by kupiqu** [comment] 2018-11-28 03:11
> Did you try some workarounds in this? https://wiki.archlinux.org/index.php/intel_graphics#Troubleshooting

I took a look but that is incompatible with xserver-xorg-video-intel-native-modesetting, that is i915 integrated with the linux kernel which seems to be recommended by ubuntu and intel

I did upgrade the kernel from 4.15 to 4.18 to see if there was any improvement, but no luck

**Comment by trmdi** [comment] 2018-11-28 03:14
> > Did you try some workarounds in this? https://wiki.archlinux.org/index.php/intel_graphics#Troubleshooting
> 
> I took a look but that is incompatible with xserver-xorg-video-intel-native-modesetting, that is i915 integrated with the linux kernel which seems to be recommended by ubuntu and intel
> 
> I did upgrade the kernel from 4.15 to 4.18 to see if there was any improvement, but no luck

Did you try `xserver-xorg-video-intel` instead of the recommended one?

**Comment by kupiqu** [comment] 2018-11-28 03:16
> Did you try xserver-xorg-video-intel instead of the recommended one?

No, I didn't want to mess with it. At least not at this time...

**Comment by trmdi** [comment] 2018-11-28 03:17
> > Did you try xserver-xorg-video-intel instead of the recommended one?
> 
> No, I didn't want to mess with it. At least not at this time...

I've just checked, I'm using it.

**Comment by kupiqu** [comment] 2018-11-28 03:17
> I've just checked, I'm using it.

Which one, Kernel or Xorg?

**Comment by trmdi** [comment] 2018-11-28 03:19
> > I've just checked, I'm using it.
> 
> Which one, Kernel or Xorg?

The non-modesetting one: `xf86-video-intel` which is not recommended by Ubuntu.

**Comment by kupiqu** [comment] 2018-11-28 03:35
No luck, at least with just the vanilla setup. Playing with options might help but that is like seeking a needle in a haystack :(

**Comment by tsujan** [comment] 2018-11-28 05:53
If it helps, the output of `inxi -G` here:
```
Graphics:  Card-1: Intel HD Graphics 530
           Card-2: NVIDIA GM107M [GeForce GTX 960M]
           Display Server: x11 (X.Org 1.19.5 ) driver: modesetting Resolution: 1920x1080@60.02hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 530 (Skylake GT2) version: 4.5 Mesa 17.2.5
```
In System Settings → Display and Monitor → Compositor, I have:

  * Enable compositing on startup = checked.
  * Animation speed slider = at the middle.
  * Scale method = Accurate.
  * Rendering backend = OpenGL 3.1.
   * vsync = Automatic.

-----------------
The Intel driver also worked fine with the following settings but I didn't test it for a long time -- instead, I chose modesetting.
```
Section "Device"
	Identifier  "Device0"
	Driver      "intel"
	BusID       "PCI:0:2:0"
	Option      "AccelMethod" "sna"
	Option      "DRI"    "true"
EndSection
```

**Comment by tsujan** [comment] 2018-11-28 05:55
EDIT: I updated the output of `inxi -G` -- had pasted an old output ;)

**Comment by kupiqu** [comment] 2018-11-28 11:55
I don't think these options in xorg will fix the issue for me, as sna and dri true are enabled by default, so setting them explicitly won't change behavior.

But, another user reported in the KDE bug that he stopped seeing the artifacts in Qt Version 5.12.0 RC1... so this may be a Qt bug in the end. Let's hope this is confirmed...

**Comment by tsujan** [comment] 2018-11-28 13:06
After this discussion, I can refer users to https://bugs.kde.org/show_bug.cgi?id=397215 , as a proof that shows this isn't about BreezeEnhanced.

I've seen not very different artifacts in Qt widgets that have translucency **only when the  value of QT_SCALE_FACTOR is non-integer** -- for example, 1.5, 2.5,.... Recently, I started to support non-integer scale factors in Kvantum and saw artifacts in widgets for which translucency was enabled, especially in menus. I found and added a workaround to Kvantum but menus and item-views weren't completely fixed by it. I can't say they are related to this issue because *they happen only with non--integer scale factors* (which I never use -- I just test them). This shows that there is a bug in Qt. Whether there is any relation between it and the current Breeze bug, I can't tell because there are too many factors at work.

BTW, I use the LTS kernel 4.19 -- I always use LTS kernels, previously 4.14.

**Comment by kupiqu** [comment] 2018-11-28 13:16
> translucency

I see, so it might be caused by translucency, not necessarily by the animation.

I guess it's difficult to understand at first sight, though, why this is different between kwin and plasma (i.e., applet-window-buttons)

**Comment by tsujan** [comment] 2018-11-28 13:39
> why this is different between kwin and plasma

I don't know but, in both cases of Breeze and non-integer scale factors, the calculations are done in terms of `qreal` (double), so that the final result is anti-aliased. It seems that, in such cases, non-integer values are replaced by wrong integers. Just a wild guess...

**Comment by kupiqu** [comment] 2018-11-28 14:55
> But, another user reported in the KDE bug that he stopped seeing the artifacts in Qt Version 5.12.0 RC1... so this may be a Qt bug in the end. Let's hope this is confirmed...

Same user reported he saw the issue again (in Qt Version 5.12), so Qt doesn't fix it

**Comment by ripefig** [comment] 2018-11-28 15:12
@tsujan 
The problem is gone after upgrading the rendering backend to OpenGL 3.1. I've only experienced this bug on OpenGL 2.0

**Comment by kupiqu** [comment] 2018-11-28 15:15
> The problem is gone after upgrading the rendering backend to OpenGL 3.1. I've only experienced this bug on OpenGL 2.0

Not in my case I suffer it in both. Try `kwin --replace` and check it again.

**Comment by ripefig** [comment] 2018-11-29 01:34
@kupiqu @tsujan. Yeah, I lies OpenGL 3 causes the same problem, just less frequently.

The artifact is probably caused by the transparency feature (which I have turned off). The little artifacts are actually transparent and blurred. The whole problem seems to go away if blur effect is disabled or if your switch to regular breeze, which doesn't support transparency.

**Comment by ripefig** [comment] 2018-12-02 20:55
@tsujan maybe consider making a version without transparency? that's what causing the bug.

**Comment by tsujan** [comment] 2018-12-02 21:04
> that's what causing the bug.

Translucency can't cause any bug.

**Comment by ripefig** [comment] 2018-12-02 21:10
hmm, but this isn't observed in the breeze decoration. the artifacts are in fact translucent. there is also a little artifact in the corner..

breeze enhanced:

![image](https://user-images.githubusercontent.com/45201036/49344979-8829d800-f68f-11e8-8cd8-5649a7e084ec.png)

vs

breeze:

![image](https://user-images.githubusercontent.com/45201036/49344997-c7582900-f68f-11e8-895f-9f1c1ff2b27f.png)

**Comment by ripefig** [comment] 2018-12-02 21:10
that's with openGL 2/3

**Comment by ripefig** [comment] 2018-12-03 02:54
I have tried it with opengl 2/3, multiple times. never encountered it.

**Comment by trmdi** [comment] 2018-12-03 03:18
> I have tried it with opengl 2/3, multiple times. never encountered it.

This bug relates a lot to the video driver. But I don't think translucency is the root cause. If it was the root cause, everyone would get the bug. That's not true.

**Comment by kupiqu** [comment] 2018-12-03 11:31
I guess @ripefig just means it as a workaround until the real root cause is identified and fixed

**Comment by kupiqu** [comment] 2018-12-03 11:39
> I guess @ripefig just means it as a workaround until the real root cause is identified and fixed

I, for one, didn't experience the issue with vanilla breeze either

**Comment by tsujan** [comment] 2018-12-03 11:51
Anyone can disable translucency in the `Opacity` setting. I won't remove that setting -- a title-bar without translucency is not an option for me.

**Comment by kupiqu** [comment] 2018-12-03 12:22
Sure. I don't think anybody asked to remove the feature. 

The setting seems not to be enough, which means that either it is not applied all around the code, or that translucency is in fact not triggering the issue, and sth else is doing it.

**Comment by tsujan** [comment] 2018-12-03 13:58
@kupiqu After reading your last comment, I found and [fixed](https://github.com/tsujan/BreezeEnhanced/commit/fdaccbe95d7ca3594c70b156b7ca1d8728b9f9eb) an issue that was totally unrelated to this. I guess it was an example of what psychologists call "free association" ;)

**Comment by tsujan** [comment] 2018-12-25 05:10
Today, I started my old Asus laptop (with broken screen - I use it with an external monitor only for testing Qt apps under gnome-shell) after 3 months to upgrade Manjaro on it and saw the artifacts reported here. Strange! The same programs (expect for gnome) and the same driver (modesetting) with two different Intel cards but I've never seen these artifacts on my main laptop (Lenovo). Actually, the artifacts are hard to reproduce on the Asus but, somtimes, I can see them when maximizing windows.

I think the bug is in KWin. KDE had also different behaviors on these two computers a year ago but in the opposite direction: it worked well on the old laptop and bad on the new one. Now, it works like a charm on Lenovo but has this problem on the older Asus!

**Comment by trmdi** [comment] 2018-12-25 05:57
> the same driver (modesetting) with two different Intel cards
What will happen if you try an older version of the driver ?

**Comment by tsujan** [comment] 2018-12-25 08:48
> What will happen if you try an older version of the driver ?

Since I start that crappy laptop once in a few months, it isn't worth the effort... I should email it to KDE devs ;)

**Comment by trmdi** [comment] 2018-12-26 16:00
Another artifact when I turn on Kwin's wobbly effect.
The line between the title bar and the window will appear when I move the window.
![test](https://user-images.githubusercontent.com/11857205/50450445-b209ae00-0960-11e9-9f93-db125587bce2.gif)

**Comment by tsujan** [comment] 2018-12-26 17:31
@trmdi That artifact is VERY old and is visible with all kinds of titlebars. KDE devs never fixed it. Because of it and because the blur effect is disabled while moving, I never use the wobbly effect.

Compiz-reloaded also has this problem with all Emerald engines except for the pixmap engine.

**Comment by trmdi** [comment] 2018-12-26 17:48
I would try reporting this bug again, it is a Kwin bug, isn't it? Is it very easy for everyone to reproduce the bug?

**Comment by tsujan** [comment] 2018-12-26 18:10
> it is a Kwin bug, isn't it?

Definitely.

> Is it very easy for everyone to reproduce the bug?

It should be. I've seen it with various computers (mine and others').

Please note that it isn't limited to the wobbly effect or translucent windows. You could see it also when you show the desktop cube. In this screenshot, the cube is shown and rotated a little:

**Closed** 2018-12-26 18:10 UTC

**Comment by tsujan** [comment] 2018-12-26 18:11
I pressed the "reopen" button inadvertently, instead of file attachment button... Closed it again

**Comment by tsujan** [comment] 2018-12-27 15:33
Oh, they made it a duplicate of https://bugs.kde.org/show_bug.cgi?id=257566 ; I had no idea that it was reported in 2011!! You know what that means ;)
